name: "setup-node"
runs:
  using: "composite"
  steps:
    - uses: pnpm/action-setup@v2
    - uses: actions/setup-node@v3
      with:
        node-version: "18.x"
        cache: pnpm
      with:
        version: "8.x"
    - run: pnpm install
      shell: bash
